# Site settings
title: BancoSol 30 años
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://gitjhordy.github.io/" # the subpath of your site, e.g. /blog/
url: "https://gitjhordy.github.io/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
